import sys
from pathlib import Path

_DOCS_EXT_DIR = Path(__file__).resolve().parent / "_ext"
_p = str(_DOCS_EXT_DIR)
if _p not in sys.path:
    sys.path.insert(0, _p)

###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = "John Bogaardt, Kenneth Hsu, et. al."
autosummary_generate = True
bibtex_bibfiles = ["library/references.bib"]
bibtex_reference_style = "author_year"
comments_config = {"hypothesis": False, "utterances": False}
copyright = "2023"
exclude_patterns = ["**.ipynb_checkpoints", ".DS_Store", "Thumbs.db", "_build"]
extensions = [
    "jupyter_book",
    "linkcode",
    "myst_nb",
    "numpydoc",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.linkcode",
    "sphinx.ext.mathjax",
    "sphinx_book_theme",
    "sphinx_comments",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_external_toc",
    "sphinx_jupyterbook_latex",
    "sphinx_multitoc_numbering",
    "sphinx_thebe",
    "sphinx_togglebutton",
    "sphinxcontrib.bibtex",
]
external_toc_exclude_missing = False
external_toc_path = "_toc.yml"
html_baseurl = ""
html_css_files = ["sidebar-toggle.css"]
html_favicon = ""
html_logo = "images/logo.png"
html_sourcelink_suffix = ""
html_static_path = ["_static"]
html_theme = "sphinx_book_theme"
html_theme_options = {
    "analytics": {
        "google_analytics_id": "",
        "plausible_analytics_domain": "",
        "plausible_analytics_url": "https://plausible.io/js/script.js",
    },
    "announcement": "",
    "extra_footer": "",
    "home_page_in_toc": True,
    "launch_buttons": {
        "binderhub_url": "",
        "colab_url": "",
        "deepnote_url": "",
        "jupyterhub_url": "",
        "notebook_interface": "classic",
        "thebe": False,
    },
    "path_to_docs": "docs",
    "repository_branch": "main",
    "repository_url": "https://github.com/casact/chainladder-python",
    "search_bar_text": "Search this website...",
    "use_edit_page_button": False,
    "use_issues_button": True,
    "use_repository_button": True,
}
html_title = "Chainladder - Python"
intersphinx_mapping = {"sklearn": ["https://scikit-learn.org/stable/", None]}
latex_engine = "pdflatex"
myst_enable_extensions = [
    "colon_fence",
    "dollarmath",
    "html_admonition",
    "linkify",
    "substitution",
]
myst_url_schemes = ["mailto", "http", "https"]
nb_execution_allow_errors = False
nb_execution_cache_path = ""
nb_execution_excludepatterns = []
nb_execution_in_temp = False
nb_execution_mode = "force"
nb_execution_timeout = 180
nb_output_stderr = "show"
numfig = True
numpydoc_show_class_members = False
pygments_style = "sphinx"
suppress_warnings = ["myst.domains"]
templates_path = ["_templates"]
use_jupyterbook_latex = True
use_multitoc_numbering = True
