name: Ruff

on:
  push:
    branches:
      - '**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ruff check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run ruff
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
        with:
          version: "0.16.1"
