name: Ruff

permissions:
  contents: read

on:
  push:
    branches:
      - '**'

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ruff check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Run ruff
        run: |
          uvx ruff@0.16.1 check --force-exclude --output-format=github .

      - name: Run ruff format
        run: |
          uvx ruff@0.16.1 format --check --diff --force-exclude .
